### PR TITLE
Fixes #69 - Gather writes are broken.

### LINKED ISSUE #69: Gather writes are broken
The implementation of `Common.write(ByteBuffer[] srcs, int offset, int length)` is faulty in case the channel is set in non-blocking mode.

When in non-blocking mode, there is no guarantee that the `write()` actually writes any byte, so the loop over the buffers must exit as soon as the write is incomplete.

### PR DESCRIPTION
**Pull request by sbordet**
Correctly looping over the buffers, returning
as soon as one of the writes is not complete.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

File: src/main/java/jnr/unixsocket/impl/Common.java [hunk 1]
```diff
@@ -121,14 +121,18 @@ int write(ByteBuffer src) throws IOException {
...
 
-        for (index = offset; index < length; index++) {
-            result += write(srcs[index]);
+        for (int index = offset; index < length; ++index) {
+            ByteBuffer buffer = srcs[index];
+            int remaining = buffer.remaining();
+            int written = write(buffer);
+            result += written;
+            if (written < remaining) {
+                break;
```
Comment (gregw) [inline src/main/java/jnr/unixsocket/impl/Common.java]: Is it correct to immediately break? rather than try again at least once?
Consider an impl that can only write a fixed size at a time (say 1024), but it can take many calls each slicing off 1024?
Isn't it better to break only when no progress is made? ie written==0

Comment (sbordet) [reply src/main/java/jnr/unixsocket/impl/Common.java]: @gregw good point. I have changed the code to reflect your review. Good?

**Comment by gregw** [comment]
@headius any chance of getting this in a release?
